Pokemon struct cleanup
pret/pokeheartgold pull request #122
Opened 2023-02-18 00:38 UTC by AsparagusEduardo

- Renamed `POKEMON` to `Pokemon`.
- Fixed placeholder `MON_DATA` names.
- Standarized pointer star positions for `Pokemon` pointers.
- Standarized most variable names using `Pokemon`.

AsparagusEduardo#6051

2023-05-11 17:48 UTC, red031000 requested changes
generally speaking, I prefer pokemon instead of mon for the variable names, since it's more explicit.

there is a discussion to be had about typedef struct vs explicit struct, I think atm we're leaning towards the latter

The renaming is good though, all caps struct names just seem weird

2023-05-20 13:22 UTC, AsparagusEduardo commented
Solved conflicts.

2023-05-20 14:34 UTC, red031000 requested changes
only thing left is mon -> pokemon, then I'm happy to merge

2023-05-20 23:05 UTC, red031000 approved these changes

2023-05-20 23:05 UTC, merged