ARM7 OS_ splitting/porting
pret/pokeheartgold pull request #18
Opened 2021-09-11 04:11 UTC by shinyquagsire23

Direct ports from pokediamond w/o changes:
 - OS_mutex
 - OS_message
 - OS_context

Minor changes:
 - OS_thread

2021-09-11 10:06 UTC, PikalaxALT requested changes

2021-09-11 10:06 UTC, PikalaxALT commented on sub/include/function_target.h
> +#ifndef GUARD_FUNCTION_TARGET_H
Use the top level sdk include paths

2021-09-13 16:50 UTC, PikalaxALT requested changes
The comments I left on the two NitroSDK headers are generally applicable to all NitroSDK headers. I despise the way the headers are organized in pokediamond, and will not permit the same structure in pokeheartgold.

2021-09-13 16:50 UTC, PikalaxALT commented on include/nitro/OS_alarm_shared.h
> +/*
move to `lib/nitro/include/os/common/alarm_shared.h`

2021-09-13 16:50 UTC, PikalaxALT commented on sub/lib/include/OS_alarm.h
> +#ifndef NITRO_SUB_OS_ALARM_H
move to `lib/nitro/include/os/ARM7/alarm.h`

2021-09-13 16:50 UTC, PikalaxALT commented on include/function_target.h
> +#ifndef GUARD_FUNCTION_TARGET_H
This project will not make use of `function_target.h` in any capacity.

2021-09-13 16:59 UTC, shinyquagsire23 commented
> The comments I left on the two NitroSDK headers are generally applicable to all NitroSDK headers. I despise the way the headers are organized in pokediamond, and will not permit the same structure in pokeheartgold.

ok yeah I kinda hated the organization as well, the comments def cleared up my confusion. Also kinda missed the entire `lib/` folder even existing so I'll refactor over to that then.

2021-09-17 14:39 UTC, PikalaxALT approved these changes

2021-09-17 14:39 UTC, merged