#208 split PR 2, rename fsys to fieldSystem
pret/pokeheartgold pull request #232
Opened 2023-08-20 17:53 UTC by red031000

split from #208 renames fsys to fieldSystem, Fsys to FieldSystem, and FieldSys to FieldSystem

2023-08-21 18:07 UTC, luckytyphlosion commented
Do we actually want this? I thought the purpose of `fsys` was that the field is used so commonly that a short term is preferable.

2023-08-21 18:07 UTC, red031000 commented
short term is not preferable, especially if it's in function names

2023-08-21 18:09 UTC, luckytyphlosion commented
That being said, I was under the impression that `fsys` was only used to refer to the variable, and FieldSystem was used everywhere else, which is my personal opinion for the naming.

2023-08-21 18:14 UTC, luckytyphlosion commented
I agree that in function names only one term should be used. So the main questions are:
- In variables/struct fields/parameters: `fsys`, `fieldSys`, or `fieldSystem`?
- In function names (and other stuff): `Fsys`, `FieldSys`, or `FieldSystem`?

However, something like this isn't as broad as the other style issues, so we can choose whatever now and revisit it later. So basically it's up to you and @adrienntindall to decide.

2023-08-21 19:29 UTC, adrienntindall commented
> I agree that in function names only one term should be used. So the main questions are:
> 
> * In variables/struct fields/parameters: `fsys`, `fieldSys`, or `fieldSystem`?
> * In function names (and other stuff): `Fsys`, `FieldSys`, or `FieldSystem`?
> 
> However, something like this isn't as broad as the other style issues, so we can choose whatever now and revisit it later. So basically it's up to you and @adrienntindall to decide.

Function names need to be FieldSystem but I prefer fsys as the local/struct variable names, however, I don't feel strongly about this

2023-08-21 19:30 UTC, red031000 commented
where possible I tend to prefer explicit names, usually the var name being the struct type in camelCase

2023-08-21 22:58 UTC, adrienntindall requested changes

2023-08-21 22:58 UTC, adrienntindall commented on include/field_use_item.h
> +    FieldSystem *fieldSystem;             // 00
spacing of comment

2023-08-21 22:58 UTC, adrienntindall commented on include/field_follow_poke.h
> +void FollowPokeFieldSystemParamSet(FieldSystem *fieldSystem, int species, u8 form, BOOL shiny, u8 gender);
FieldSystem_SetFollowPokeParam?

2023-08-22 08:31 UTC, adrienntindall approved these changes

2023-08-22 08:31 UTC, merged