Decompile trainer_memo.c
pret/pokeheartgold pull request #254
Opened 2023-09-29 04:47 UTC by abaresk

2023-09-30 19:10 UTC, adrienntindall requested changes

2023-09-30 19:55 UTC, abaresk commented on src/trainer_memo.c
> +    switch (var1) {
Added a name for the variable and the function. Since the locations aren't documented, I'm holding off on defining any constants

2023-09-30 19:55 UTC, abaresk commented on include/constants/events.h
> +#define EVENT_ARCEUS_UNK1        1
Updated, renamed to `EVENT_ARCEUS_MOVIE_GIFT` as it was distributed in theaters / retail stores for the Arceus movie. Open to other names

2023-09-30 23:07 UTC, adrienntindall commented on src/trainer_memo.c
> +    switch (var1) {
They are documented, check the messages the constants point to and you'll see which case is which fairly easily

2023-10-01 04:31 UTC, cbt6 commented on src/trainer_memo.c
> +                if (GetMonData(mon, MON_DATA_MET_LOCATION, NULL) == sub_02017FE4(MAPSECTYPE_NORMAL, 0x56)) {
```suggestion
                if (GetMonData(mon, MON_DATA_MET_LOCATION, NULL) == sub_02017FE4(MAPSECTYPE_NORMAL, MAPSEC_HALL_OF_ORIGIN)) {
```

2023-10-02 16:56 UTC, abaresk commented on src/trainer_memo.c
> +    switch (var1) {
Updated

2023-10-08 14:02 UTC, adrienntindall requested changes

2023-10-08 14:02 UTC, adrienntindall commented on src/trainer_memo.c
> +    switch (var1) {
This is still unadressed

2023-10-08 14:04 UTC, adrienntindall approved these changes

2023-10-08 23:57 UTC, merged