Decompile overlay_25
pret/pokeheartgold pull request #258
Opened 2023-10-17 02:09 UTC by cbt6

2023-10-17 17:10 UTC, tgsm requested changes

2023-10-17 17:10 UTC, tgsm commented on src/overlay_25.c
> +            MIi_CpuCopy16(String_cstr(otName), set->trainer.otName, length * sizeof(u16));
```suggestion
            MI_CpuFill16(set->trainer.otName, 0xffff, (PLAYER_NAME_LENGTH + 1) * sizeof(u16));
            MI_CpuCopy16(String_cstr(otName), set->trainer.otName, length * sizeof(u16));
```

2023-10-17 17:10 UTC, tgsm commented on src/overlay_25.c
> +            MIi_CpuCopy16(String_cstr(name), trainerHouseMon->nickname, length * sizeof(u16));
```suggestion
            MI_CpuFill16(trainerHouseMon->nickname, 0xffff, POKEMON_NAME_LENGTH * sizeof(u16));
            MI_CpuCopy16(String_cstr(name), trainerHouseMon->nickname, length * sizeof(u16));
```

2023-10-17 17:10 UTC, tgsm commented on src/overlay_25.c
> +        MIi_CpuCopy16((u16*)&(trainerHouse->sets[trainerNum].trainer.introMessage), (u16*)&intro, sizeof(MAIL_MESSAGE));
```suggestion
        MI_CpuCopy16(&temp, &intro, sizeof(MAIL_MESSAGE));
    } else {
        MI_CpuCopy16(&(trainerHouse->sets[trainerNum].trainer.introMessage), &intro, sizeof(MAIL_MESSAGE));
```

2023-10-18 00:43 UTC, tgsm submitted a review, later dismissed

2023-10-18 02:00 UTC, red031000 requested changes
few small things, need discussing whether appropriate

2023-10-18 14:50 UTC, cbt6 commented on src/overlay_25.c
> +    setup->battleBg = 6;
To be done in a separate PR.

2023-10-20 14:26 UTC, red031000 requested changes
I dont see where you renamed the scrcmd in scrcmd.c? I see it in the headers but not in the c file? possible that github is playing up?

2023-10-20 14:28 UTC, cbt6 commented
Are you referring to `ScrCmd_ShowTrainerHouseIntroMessage`? That's in `src/overlay_25.c`

2023-10-20 14:36 UTC, red031000 commented
odd that it's not in an scrcmd file

2023-10-20 14:36 UTC, red031000 approved these changes

2023-10-20 14:36 UTC, merged