replaced some generic argument names with more descriptive names
pret/pokeheartgold pull request #276
Opened 2023-12-13 20:25 UTC by turtleisaac

As part of the commit contained in this pull request, I have replaced generic argument names (i.e. "arg0," "arg1,", etc...) for field scripting commands with more descriptive names that reflect what the value of the argument means.

These changes mostly relate to commands which involve overworld objects, but also include a trainer battle goto_if command. The changes made were according to the [Kingdom of DS Hacking Scrcmd Document](https://docs.google.com/spreadsheets/d/1rcrCz9Y5HXdD9vVSmkACX19I9Jid4dzFTD0PXaIDg2w/edit#gid=1350726349) and my own personal knowledge of what arguments these commands should take, along with context for the `goto_if_trainer_defeated` command since all of the other `goto_if` commands in Script.inc use `dest` as their argument name for the function to jump to.

For the `apply_movement` command, I used `sub` as the destination name, as it is more akin to one of the `call` or `call_if` commands, as execution returns to this point once the movement is started in parallel.

2023-12-13 21:39 UTC, red031000 commented
yeah we're not using `overworld` for events, it's very very poorly descriptive

2023-12-13 21:43 UTC, red031000 commented
diamond (and likely HG, not sure if I ported yet) uses LocalMapObject for events, much better imo than Overworld, cause that really does not mean anything, at least LocalMapObject is descriptive to what it is

2023-12-15 07:30 UTC, adrienntindall commented
> diamond (and likely HG, not sure if I ported yet) uses LocalMapObject for events, much better imo than Overworld, cause that really does not mean anything, at least LocalMapObject is descriptive to what it is

Ditto on this, I understand where the terminology 'Overworld' comes from but Object is a much more common term outside of the rom hacking community.

2023-12-17 22:25 UTC, PikalaxALT commented
Agree with the above, suggest `objectId`.

2023-12-24 02:59 UTC, red031000 requested changes

2023-12-24 02:59 UTC, red031000 commented on asm/macros/script.inc
> +	.macro apply_movement overworld, sub
delet overworld (see comments for suggestions)

2024-03-26 00:44 UTC, PikalaxALT commented
Closing due to inactivity

2024-03-26 00:44 UTC, closed without merging