clean up move_relearner.c
pret/pokeheartgold pull request #282
Opened 2023-12-24 05:32 UTC by red031000

WIP

2023-12-24 22:52 UTC, red031000 commented
build should work now

2023-12-25 19:52 UTC, red031000 commented
seeking opinions on the renaming of wotbl, I suggest lvlUpTable

2023-12-30 00:21 UTC, adrienntindall commented
> seeking opinions on the renaming of wotbl, I suggest lvlUpTable

learnSetTable, moveLearnTable, levelUpTable, etc

2024-02-02 23:27 UTC, red031000 commented
ready for review

2024-02-03 03:56 UTC, adrienntindall requested changes

2024-02-03 03:56 UTC, adrienntindall commented on src/move_relearner.c
> +    u16 species = (u16)GetMonData(mon, MON_DATA_SPECIES, NULL);
casts here are unnecessary

2024-02-03 03:56 UTC, adrienntindall commented on src/pokemon.c
> +    levelUpLearnset = AllocFromHeap(HEAP_ID_DEFAULT, 22 * sizeof(u16));
const for LEARNED_MOVES_MAX = 22?

2024-02-05 01:05 UTC, adrienntindall approved these changes

2024-02-05 01:15 UTC, merged