Title Screen
pret/pokeheartgold pull request #295
Opened 2024-01-20 22:49 UTC by PikalaxALT

the first part of overlay_60

2024-02-04 19:04 UTC, red031000 requested changes
a few things

2024-02-04 20:01 UTC, PikalaxALT commented on src/title_screen.c
> +static fx32 fx32_abs(fx32 x) {
i didn't see anything like this defined in sdk

2024-02-04 20:02 UTC, PikalaxALT commented on src/title_screen.c
> +#if 0
I mentioned it in the discord earlier but this is code I wrote to give the player exclusive control over the camera here

2024-02-04 20:06 UTC, PikalaxALT commented on src/title_screen.c
> +    GfGfxLoader_GXLoadPal(NARC_demo_title_titledemo, res2, GF_PAL_LOCATION_SUB_BGEXT, (enum GFPalSlotOffset)0x4000, 0, heapID);
i disagree, i think the enum should be removed

2024-02-04 20:10 UTC, PikalaxALT commented on src/title_screen.c
> +        FX32_ONE, 0, 0, 0, FX32_ONE, 0, 0, 0, FX32_ONE,
tell that to your .clang-format

2024-02-04 20:11 UTC, red031000 commented on src/title_screen.c
> +static fx32 fx32_abs(fx32 x) {
I mean fair, especially if it's compiled in, I'm just more suprised that it is here and not in like a general fx file

2024-02-04 20:11 UTC, PikalaxALT commented on src/title_screen.c
> +    GraphicsBanks graphicsBanks = {
from a pure style perspective you're right, but this data is copied onto the stack, strongly implying that this is how gf wrote it. that plus the equivalent code in platinum does the exact same thing.

2024-02-04 20:12 UTC, PikalaxALT commented on src/title_screen.c
> +                GF_SetVolumeBySeqNo(1, 48);
feel free to document the sound routines and structs

2024-02-04 20:12 UTC, PikalaxALT commented on src/title_screen.c
> +    TitleScreen_DeinitBgs(data);
Please suggest an alternative

2024-02-04 20:13 UTC, PikalaxALT commented on src/title_screen.c
> +            *state = (int)TITLESCREEN_MAIN_START_MUSIC;
compiler throws an error without it. i don't make the rules.

2024-02-04 20:13 UTC, red031000 commented on src/title_screen.c
> +            *state = (int)TITLESCREEN_MAIN_START_MUSIC;
compiler is dumb, that's ok then

2024-02-04 20:14 UTC, red031000 commented on src/title_screen.c
> +    TitleScreen_DeinitBgs(data);
DeleteBGs? UnloadBGs?
those sound better than Deinit to me

2024-02-04 20:14 UTC, red031000 commented on src/title_screen.c
> +                GF_SetVolumeBySeqNo(1, 48);
fair, considering this out of scope then

2024-02-04 20:14 UTC, PikalaxALT commented on src/title_screen.c
> +    sub_0200FBF4(PM_LCD_TOP, RGB_WHITE);
the corresponding code in retsam is ||src/system/brightness.c|| if you want to try and adapt that

2024-02-04 20:15 UTC, red031000 commented on src/title_screen.c
> +    GraphicsBanks graphicsBanks = {
I know that it probably is how GF wrote it, but also consider
GF is dumb and writes bad code

I'd greatly perfer data to be outside of funcs, if it still matches

2024-02-04 20:15 UTC, red031000 commented on src/title_screen.c
> +    GraphicsBanks graphicsBanks = {
and plat doesn't count here, considering that's copied from GF

2024-02-04 20:16 UTC, PikalaxALT commented on src/title_screen.c
> +    PaletteData_FadePalettesTowardsColorStep(animData->plttData, 2, 0xFF00, 160, animData->glowFadeStep, RGB(12, 12, 12));
are you talking about transparentBit and opaqueBit? these are masks for the palette slots which don't have informative enums

2024-02-04 20:16 UTC, red031000 commented on src/title_screen.c
> +        FX32_ONE, 0, 0, 0, FX32_ONE, 0, 0, 0, FX32_ONE,
yeah I understand clang format, normally I'd agree, however, matrices are a bit of an exception, if I could figure out how to code that into clang-format I would, but I don't know how

2024-02-04 20:17 UTC, red031000 commented on src/title_screen.c
> +    sub_0200FBF4(PM_LCD_TOP, RGB_WHITE);
yeah no thanks, if you say it is indeed RGB then I'll take your word for it

2024-02-04 20:17 UTC, red031000 commented on src/title_screen.c
> +    GfGfxLoader_GXLoadPal(NARC_demo_title_titledemo, res2, GF_PAL_LOCATION_SUB_BGEXT, (enum GFPalSlotOffset)0x4000, 0, heapID);
ehh, disagree myself on that, having palette slots directly labelled and made clear is an advantage imo

2024-02-04 20:18 UTC, red031000 commented on src/title_screen.c
> +    BG_LoadPlttData(3, &color1, sizeof(u16), 0x42);
fair enough, GF code weird but ok

2024-02-04 20:19 UTC, PikalaxALT commented on src/title_screen.c
> +    GfGfxLoader_GXLoadPal(NARC_demo_title_titledemo, res2, GF_PAL_LOCATION_SUB_BGEXT, (enum GFPalSlotOffset)0x4000, 0, heapID);
not really, it's just namespace clutter at this point

2024-02-04 20:19 UTC, red031000 commented on src/title_screen.c
> +    PaletteData_FadePalettesTowardsColorStep(animData->plttData, 2, 0xFF00, 160, animData->glowFadeStep, RGB(12, 12, 12));
ignore me, I just looked at the func itself, only thing is given that 2 is a bit, should probably be 0x02 instead

2024-02-04 20:20 UTC, red031000 commented on src/title_screen.c
> +#if 0
ok fair, imo should still be in a branch of itself, or maybe #if DEBUG instead

2024-02-05 15:48 UTC, adrienntindall commented on asm/overlay_112.s
> +	.public gApplication_TitleScreen
ideally this should go in the .inc file but it's nbd

2024-02-05 17:02 UTC, adrienntindall requested changes

2024-02-05 17:02 UTC, adrienntindall commented on src/title_screen.c
> +#if 0
yeah right now the project should be focused on decomp, extension is fine but not in the main branch

2024-02-06 01:50 UTC, PikalaxALT commented on src/title_screen.c
> +#if 0
perhaps i should create a define for this: `TITLE_SCREEN_CAMERA_DEBUG` sound ok?

2024-02-13 21:27 UTC, red031000 requested changes, later dismissed

2024-02-13 21:27 UTC, red031000 commented on src/title_screen.c
> +    GraphicsBanks graphicsBanks = {
please move data outside of func

2024-02-18 13:06 UTC, red031000 approved these changes, later dismissed

2024-02-20 21:01 UTC, adrienntindall approved these changes, later dismissed

2024-02-21 05:23 UTC, adrienntindall approved these changes

2024-02-21 05:23 UTC, merged