cleanup follow_mon.c
pret/pokeheartgold pull request #303
Opened 2024-02-19 17:06 UTC by red031000

2024-02-21 05:22 UTC, adrienntindall requested changes

2024-02-21 05:32 UTC, red031000 commented on src/follow_mon.c
> +    u16 b = (u16)(param >> 10) << 10;
isnt u16 a shift by...16, not 10?

2024-02-21 05:32 UTC, red031000 commented on src/follow_mon.c
> +static BOOL FollowMon_DiglettPermissionCheck(int mapNo) {
wdym? that's only for data

2024-02-21 05:33 UTC, adrienntindall commented on src/follow_mon.c
> +static BOOL FollowMon_DiglettPermissionCheck(int mapNo) {
wait Im dumb ignore me

2024-02-22 18:49 UTC, red031000 commented on src/follow_mon.c
>      u8 data[4];
not entirely sure if that'd work with reading the narc, and if it would, idk what the fields would be

2024-02-26 00:48 UTC, red031000 commented on src/follow_mon.c
>      u8 data[4];
marking as out of scope for now, may come back to it when more info has been got

2024-02-26 01:04 UTC, adrienntindall approved these changes

2024-02-26 01:04 UTC, adrienntindall commented on include/field_system.h
> +typedef struct FieldSystemUnk108 {
It looks like it gets used in functions called by interacting with follower mons

2024-02-26 01:07 UTC, red031000 commented on include/field_system.h
> +typedef struct FieldSystemUnk108 {
I'm still not 100% on it, if you have a suggestion for the name I'd happily apply it

2024-02-26 01:07 UTC, adrienntindall commented on include/field_system.h
> +typedef struct FieldSystemUnk108 {
hmmm, it's nbd since we can just doc it when we get to hat follower interaction parts of the asm decomp

2024-02-26 01:08 UTC, merged