Sync documentation from speedchoice
pret/pokeheartgold pull request #336
Opened 2024-09-23 23:58 UTC by PikalaxALT

2024-10-03 16:24 UTC, adrienntindall requested changes
Would prefer more documentation but I don't think that's feasible as of right now

2024-10-03 16:24 UTC, adrienntindall commented on include/battle/battle.h
> +    struct {
why?

2024-10-03 16:24 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +        flag &= 0xC00;
would prefer some consts here even if theyre all unown, ie #def HP_BAR_FLAG_4 (1 << 4) type things

2024-10-03 16:24 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +    renderer   = ov12_0223A8E4(hpBar->bsys);
ov12_0223A8E4 -> BattleSystem_GetSpriteRenderer

2024-10-03 16:24 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +    gfxHandler = ov12_0223A8EC(hpBar->bsys);
ov12_0223A8EC -> BattleSystem_GetGfxHandler

2024-10-03 16:24 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +            r4->x + x - ov12_0226D368[hpBar->type],
ov12_0226D368 -> sHpBarXOffsets

2024-10-03 16:24 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +            r4->x + x - ov12_0226D368[hpBar->type],
or sHpBoxXOffsets, etc, whatever you want

2024-10-03 16:24 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +    {
brackets required to match?

2024-10-03 16:34 UTC, PikalaxALT commented on src/battle/battle_hp_bar.c
> +    {
iirc yes

2024-10-07 02:56 UTC, adrienntindall approved these changes

2024-10-07 02:56 UTC, adrienntindall commented on src/battle/battle_hp_bar.c
> +    const UnkTemplate_0200D748 *tmplate;
tmplate -> template

2024-10-07 02:59 UTC, merged