Unk 020183 f0
pret/pokeheartgold pull request #345
Opened 2024-10-20 03:45 UTC by PikalaxALT

2024-10-28 03:48 UTC, adrienntindall requested changes

2024-10-28 03:48 UTC, adrienntindall commented on include/berry_pots_app_internal.h
> +    TouchscreenListMenuSpawner *menuSpawner;
is spawner really the best term here?

2024-10-28 03:48 UTC, adrienntindall commented on include/mail_misc.h
> +void sub_02090E5C(EasyChatArgs *args, MenuInputState a1);
a1 -> menuInputState

2024-10-28 03:48 UTC, adrienntindall commented on include/menu_input_state.h
> +typedef struct MenuInputStateMgr {
Why is this a struct and can you get it to match without it?

2024-10-28 03:48 UTC, adrienntindall commented on include/options_app.h
> +    MenuInputStateMgr *unk8;
unk8 -> menuInputStateMgr
Also if Mgr = Manager we should write it as Man (shorthand) or straight up in long hand

2024-10-28 03:48 UTC, adrienntindall commented on include/overlay_55.h
> +    MenuInputStateMgr *unk8;
name unk8

2024-10-28 03:48 UTC, adrienntindall commented on include/party_menu.h
> +void sub_0207CB3C(PartyMenu *partyMenu, MenuInputState a1);
a1 -> menuInputState

2024-10-28 03:48 UTC, adrienntindall commented on src/alph_puzzle.c
> +    data->menuIgnoreTouchFlag = MenuInputStateMgr_GetState(data->args->menuInputStatePtr);
TouchFlag -> TouchState?

2024-10-28 03:48 UTC, adrienntindall commented on src/application/view_photo.c
> +            viewPhoto->lastInputWasTouch = MENU_INPUT_STATE_BUTTONS;
lastInputWasTouch -> inputState

2024-10-28 03:48 UTC, adrienntindall commented on src/options_app.c
> +    data->menuInputPtr        = args->unk8;
unk8 -> menuInputPtr

2024-10-28 03:48 UTC, adrienntindall commented on src/options_app.c
> +    data->unk320              = MenuInputStateMgr_GetState(data->menuInputPtr);
unk320 -> menuInputState

2024-10-28 03:48 UTC, adrienntindall commented on src/party_menu.c
> +static int sub_0207AC70(PartyMenu *partyMenu, MenuInputState a1);
name a1

2024-10-28 03:48 UTC, adrienntindall commented on src/party_menu.c
> +static int sub_0207AC70(PartyMenu *partyMenu, MenuInputState a1) {
name a1

2024-10-28 03:48 UTC, adrienntindall commented on src/party_menu.c
> +void sub_0207CB3C(PartyMenu *partyMenu, MenuInputState a1) {
name a1

2024-10-28 03:48 UTC, adrienntindall commented on src/touch_save_app.c
> +static void ov30_0225DC00(MenuInputStateMgr *stateMgr, MenuInputState state) {
can prolly name this as just a static version of set state

2024-10-28 03:48 UTC, adrienntindall commented on src/touchscreen_list_menu.c
> +TouchscreenListMenuSpawner *TouchscreenListMenuSpawner_Create(HeapID heapId, PaletteData *paletteData) {
Ideally just rename spawner to manager and remove the current manager as a struct

2024-10-28 23:08 UTC, PikalaxALT commented on include/berry_pots_app_internal.h
> +    TouchscreenListMenuSpawner *menuSpawner;
i'm open to suggestions

2024-10-30 04:14 UTC, adrienntindall commented on include/menu_input_state.h
> +typedef struct MenuInputStateMgr {
considering this is gf, yes

2024-10-30 04:16 UTC, adrienntindall approved these changes

2024-10-30 04:16 UTC, merged