map_header: Minor improvements
pret/pokeheartgold pull request #362
Opened 2024-12-26 21:22 UTC by tgsm

I stole a couple of function names from pokeplatinum.

I recommend reviewing commit-by-commit.

2024-12-26 22:36 UTC, red031000 commented
I hope this doesn't conflict with my WIP map renaming PR...

2024-12-26 22:55 UTC, adrienntindall requested changes
I will simply trust that the data file too big to review non locally is fine and just a ton of variable changes

2024-12-26 22:55 UTC, adrienntindall commented on asm/overlay_01_021E90C0.s
> +	bl MapHeader_IsBuilding
MapHeader_IsBuilding -> MapHeader_IsInBuilding

2024-12-26 22:55 UTC, adrienntindall commented on src/map_header.c
> +    return sMapHeaders[mapId].unk_12_C;
unk_12_C ->momCallIntroParam or similar

2024-12-26 22:55 UTC, adrienntindall commented on src/map_header.c
> +BOOL MapHeader_IsKanto(u32 mapId) {
IsKanto -> IsInKanto?

2024-12-30 00:53 UTC, adrienntindall approved these changes

2024-12-30 00:54 UTC, merged