Decompile unk_0203170C
pret/pokeheartgold pull request #47
Opened 2022-02-27 15:15 UTC by abaresk

2022-02-27 15:45 UTC, tgsm requested changes

2022-02-27 15:45 UTC, tgsm commented on src/unk_0203170C.c
> +    a1->unk1 = 2;
```suggestion
    a1->unk1 = GAME_LANGUAGE;
```

2022-02-27 15:45 UTC, tgsm commented on include/unk_0203170C.h
> +    u8 unk1;
```suggestion
    u8 version;
    u8 language;
```

2022-02-27 15:45 UTC, tgsm commented on include/unk_0203170C.h
> +    u16 unk8[OT_NAME_LENGTH + 1];
```suggestion
    u32 otid;
    u16 name[OT_NAME_LENGTH + 1];
```

2022-02-27 16:05 UTC, abaresk commented
Updated field names in structs

2022-02-27 16:27 UTC, tgsm submitted a review, later dismissed

2022-02-27 19:59 UTC, PikalaxALT requested changes

2022-02-27 20:58 UTC, abaresk commented
Fixed

2022-03-01 15:42 UTC, PikalaxALT approved these changes

2022-03-01 15:43 UTC, merged