Decompile Unk_0255418.s
pret/pokeheartgold pull request #62
Opened 2022-03-21 05:28 UTC by adrienntindall

Time functions, daily resets, and apricorn tree functions;

2022-03-21 06:47 UTC, tgsm commented on src/unk_02055418.c
> +    UnkStruct_020556FC* unkPtr = AllocFromHeap(unkB, sizeof(UnkStruct_020556FC));
`unkB` is a HeapID

2022-03-21 07:06 UTC, adrienntindall commented on src/unk_02055418.c
> +    UnkStruct_020556FC* unkPtr = AllocFromHeap(unkB, sizeof(UnkStruct_020556FC));
Fixed! Thanks for the catch!

2022-03-21 22:43 UTC, tgsm requested changes
There's also a lot of implicit declarations here

2022-03-21 23:40 UTC, PikalaxALT requested changes

2022-03-21 23:40 UTC, PikalaxALT commented on include/unk_02014DA0.h
> +#include "library/spl.h"
Revert this

2022-03-21 23:40 UTC, PikalaxALT commented on src/unk_02055418.c
> +    if (!sysinfo->initialized) return;
```suggestion
    if (!sysinfo->initialized) {
        return;
    }
```

2022-03-21 23:40 UTC, PikalaxALT commented on src/unk_02055418.c
> +    if (minutes <= 0) return;
```suggestion
    if (minutes <= 0) {
        return;
    }
```

2022-03-21 23:40 UTC, PikalaxALT commented on src/unk_02055418.c
> +    if (sub_02055780(fsys, mapObject) != TRUE) return FALSE;
```suggestion
    if (sub_02055780(fsys, mapObject) != TRUE) {
        return FALSE;
    }
```

2022-03-22 12:06 UTC, PikalaxALT approved these changes

2022-03-23 07:39 UTC, tgsm approved these changes

2022-03-23 07:39 UTC, merged