decompiled unk_02097720.s
pret/pokeheartgold pull request #69
Opened 2022-03-29 13:06 UTC by dyedquartz

2022-03-29 13:15 UTC, PikalaxALT requested changes

2022-03-29 13:15 UTC, PikalaxALT commented on src/unk_02097720.c
> +    MI_CpuFill8(data, 0, 0xc);
```suggestion
    MI_CpuClear8(data, sizeof(Unknown_02097720));
```

2022-03-29 13:15 UTC, PikalaxALT commented on include/unk_02097720.h
> +    u16* unknown_1;
Field names, if unknown, should reflect the byte offset within the struct (in this case, 4).

2022-03-29 13:15 UTC, PikalaxALT commented on src/unk_02097720.c
> +        env->unknown_0 += 1;
```suggestion
        env->unknown_0++;
```

2022-03-29 13:15 UTC, PikalaxALT commented on src/unk_02097720.c
> +        if(FieldSys_ApplicationIsRunning(fsys) == FALSE) {
space after `if`, `while`, etc.

2022-03-29 13:15 UTC, PikalaxALT commented on src/unk_02097720.c
> +            (*env->unknown_1) = env->unknown_2[0xe];
```suggestion
            *env->unknown_1 = env->unknown_2[0xe]; // env->unknown_2 could be a struct
```

2022-03-29 13:57 UTC, PikalaxALT requested changes

2022-03-29 13:57 UTC, PikalaxALT commented on src/unk_02097720.c
> +    Unknown_02097720 *data = AllocFromHeapAtEnd(0xb, sizeof(Unknown_02097720));
```suggestion
    Unknown_02097720 *data = AllocFromHeapAtEnd(11, sizeof(Unknown_02097720));
```

If it's a small number, represent it as decimal.
If there's a defined enum or constant for this value which fits the context, use that instead.
If it's a flag array and the bitmasks are named, use those bitmasks separated by the bitwise or operator (`|`).

2022-04-01 12:23 UTC, PikalaxALT submitted a review, later dismissed

2022-04-01 15:25 UTC, tgsm requested changes

2022-04-01 15:25 UTC, tgsm commented on include/unk_02097720.h
> +    UnkStruct_Ov02_0224E4EC* unknown_8; // most likely a struct pointer
This comment is redundant

2022-04-01 15:25 UTC, tgsm commented on include/overlay_02.h
> +
Extra newline

2022-04-04 16:17 UTC, tgsm submitted a review, later dismissed

2022-04-04 17:08 UTC, merged