Decomp scrcmd_15 -> scrcmd_party
pret/pokeheartgold pull request #73
Opened 2022-04-01 18:35 UTC by Admiral-Fish

2022-04-01 20:40 UTC, PikalaxALT requested changes
In general:
- Arguments which expect a pointer but are passed 0, should be passed NULL
- Except where required to match, BOOL return values should be written accordingly
- Values which are taken to be boolean, even when they're not BOOL, should be set using TRUE or FALSE as appropriate.

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +        *species = 0;
```suggestion
        *species = SPECIES_NONE;
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +        *mine = 0;
```suggestion
        *mine = FALSE;
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +        *mine = 1;
```suggestion
        *mine = TRUE;
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +    *hasMove = 0;
```suggestion
    *hasMove = FALSE;
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +        *hasMove = 1;
```suggestion
        *hasMove = TRUE;
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +        if (GetMonData(pokemon, MON_DATA_IS_EGG, 0) != 0) {
```suggestion
        if (GetMonData(pokemon, MON_DATA_IS_EGG, 0)) {
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +    if (GetMonData(pokemon, MON_DATA_IS_EGG, 0) == 0) {
```suggestion
    if (!GetMonData(pokemon, MON_DATA_IS_EGG, 0)) {
```

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +    *type1 = GetMonData(pokemon, MON_DATA_TYPE_1, 0);
```suggestion
    *type1 = GetMonData(pokemon, MON_DATA_TYPE_1, NULL);
``` and everywhere else

2022-04-01 20:40 UTC, PikalaxALT commented on src/scrcmd_party.c
> +    if (GetMonData(pokemon, MON_DATA_MOVE1, 0) != 0) {
```suggestion
    if (GetMonData(pokemon, MON_DATA_MOVE1, NULL) != MOVE_NONE) {
```

2022-04-01 23:30 UTC, Admiral-Fish commented
`GetMonData(pokemon, MON_DATA_FATEFUL_ENCOUNTER, NULL) == TRUE`
This was required to match

`GetMonData(pokemon, MON_DATA_HP, NULL) != 0`
I left this as is as HP is not a BOOL.

2022-04-03 12:17 UTC, PikalaxALT approved these changes

2022-04-03 14:24 UTC, merged