Add m2ctx tool
pret/pokeheartgold pull request #75
Opened 2022-04-02 14:45 UTC by abaresk

This is useful for generating context files for [decomp.me](https://decomp.me).

2022-04-02 17:10 UTC, PikalaxALT reviewed
I personally would replace this with a bash script rather than python.

2022-04-02 17:10 UTC, PikalaxALT commented on tools/m2ctx/m2ctx.py
> +            if directory == dirname:
```suggestion
        if dirname in dirs:
```

2022-04-02 17:10 UTC, PikalaxALT commented on tools/m2ctx/m2ctx.py
> +    for root, dirs, files in os.walk(directory):
might be faster to use the `glob` module?

2022-04-02 17:10 UTC, PikalaxALT commented on tools/m2ctx/m2ctx.py
> +    outfile.close()
```suggestion
    tmp_file.write(output)
```

2022-04-02 19:37 UTC, abaresk commented
Switched to a bash script

2022-04-02 20:53 UTC, PikalaxALT requested changes

2022-04-02 20:53 UTC, PikalaxALT commented on tools/m2ctx/m2ctx.sh
> +    sed '/__STDC__\|__STDC_VERSION__\|__STDC_VERSION__\|__STDC_HOSTED__/d' $TMP_DECLARES > $OUT_FILE
No need to use temp files, just pipe

```suggestion
    grep "^#include " "$1" | $GCC $FLAGS $INCLUDES $DEFINES $TMP_IMPORTS -x c - | sed '/__STDC__\|__STDC_VERSION__\|__STDC_VERSION__\|__STDC_HOSTED__/d' > $OUT_FILE
```

2022-04-03 12:09 UTC, PikalaxALT approved these changes

2022-04-03 12:09 UTC, merged