Port use_item_on_mon from pokediamond
pret/pokeheartgold pull request #76
Opened 2022-04-05 05:07 UTC by Admiral-Fish

2022-04-05 15:02 UTC, PikalaxALT requested changes

2022-04-05 15:02 UTC, PikalaxALT commented on src/use_item_on_mon.c
> +{
```suggestion
BOOL CanUseItemOnPokemon(POKEMON * pokemon, u16 itemID, s32 moveIdx, HeapID heapID) {
```

2022-04-05 15:02 UTC, PikalaxALT commented on src/use_item_on_mon.c
> +        else if (dDefEv < 0) {
```suggestion
        } else if (dDefEv < 0) {
```

2022-04-09 20:39 UTC, tgsm requested changes

2022-04-09 20:39 UTC, tgsm commented on src/use_item_on_mon.c
> +{
```suggestion
s32 TryModEV(s32 ev, s32 evSum, s32 by) {
```

2022-04-09 20:39 UTC, tgsm commented on src/use_item_on_mon.c
> +{
```suggestion
void RestoreMonHPBy(POKEMON *pokemon, u32 hp, u32 maxHp, u32 restoration) {
```

2022-04-09 20:39 UTC, tgsm commented on src/use_item_on_mon.c
> +{
```suggestion
void HealParty(PARTY * party) {
```

2022-04-09 20:39 UTC, tgsm commented on src/use_item_on_mon.c
> +    else if (GetItemAttr_PreloadedItemData(itemData, ITEMATTR_HP_RESTORE) && hp != 0 && hp < GetMonData(pokemon, MON_DATA_MAXHP, NULL)) {
```suggestion
    } else if (GetItemAttr_PreloadedItemData(itemData, ITEMATTR_HP_RESTORE) && hp != 0 && hp < GetMonData(pokemon, MON_DATA_MAXHP, NULL)) {
```

2022-04-13 03:19 UTC, tgsm reviewed
Missed this one, sorry. Otherwise looks fine to me

2022-04-13 03:19 UTC, tgsm commented on src/use_item_on_mon.c
> +                pp = maxPp;
```suggestion
            if (pp > maxPp) {
                pp = maxPp;
            }
```

2022-04-13 19:13 UTC, tgsm approved these changes

2022-04-17 15:57 UTC, PikalaxALT approved these changes

2022-04-18 00:18 UTC, merged