Decompile unk_02090C94
pret/pokeheartgold pull request #85
Opened 2022-05-02 17:55 UTC by abaresk

2022-05-05 05:23 UTC, tgsm requested changes

2022-05-05 05:23 UTC, tgsm commented on src/mail_misc.c
> +        msg2->fields[1] = a0->mailMessage.fields[1];
```suggestion
        *msg2 = a0->mailMessage;
```

2022-05-05 05:23 UTC, tgsm commented on src/mail_misc.c
> +    a0->mailMessage.fields[1] = msg2->fields[1];
```suggestion
    a0->mailMessage = *msg2;
```

2022-05-05 05:23 UTC, tgsm commented on src/mail_misc.c
> +    if (a0 == NULL || a0->unk24 == 0) return 0;
```suggestion
    if (a0 == NULL || a0->unk24 == 0) {
        return 0;
    }
```

2022-05-05 05:23 UTC, tgsm commented on src/unk_02091054.c
> +    if (idx < 0x32 || idx > 0x4d) return FALSE;
```suggestion
    if (idx < 0x32 || idx > 0x4d) {
        return FALSE;
    }
```

2022-05-05 05:23 UTC, tgsm commented on src/unk_02091054.c
> +    return ((u32)(ptr->unk3 << 0x18) >> 0x1a);
This smells like a bitfield

2022-05-05 05:23 UTC, tgsm commented on src/mail_misc.c
> +    a0->mailMessage.fields[1] = mailMessage->fields[1];
```suggestion
    a0->mailMessage = *mailMessage;
```

2022-05-06 19:40 UTC, PikalaxALT submitted a review, later dismissed

2022-05-06 19:40 UTC, PikalaxALT commented on src/mail_misc.c
> +    Mail_SetNewMessageDetails(ptr->mail, -1, partyIdx, saveData);
```suggestion
    Mail_SetNewMessageDetails(ptr->mail, MAIL_NONE, partyIdx, saveData);
```

2022-05-06 19:40 UTC, PikalaxALT commented on src/unk_02091054.c
> +extern Unk02091054 _02105F04[81];
```suggestion
extern const Unk02091054 _02105F04[81];
```

2022-05-07 17:17 UTC, PikalaxALT commented on src/unk_02091054.c
> +extern Unk02091054 _02105F04[81];
Now that you've marked this `const`, you can port the data from asm to here.

2022-09-02 16:14 UTC, merged